# Generated by Django 3.0.6 on 2021-06-07 17:44

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=employee.models.renamed_photo),
        ),
    ]
